name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  deploy:
    strategy:
      matrix:
        node-version: ['16']
    runs-on: ubuntu-latest
    env:
      USERNAME: "FnanenDB[bot] 🤖"
      USEREMAIL: "actions@github.com"
      OUTPUT: data
      DUMP: fnanendb.json
      DEBUG: true

    steps:
      - uses: technote-space/auto-cancel-redundant-job@v1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run, commit, and push
        run: |
          mkdir $OUTPUT
          npm install
          node scraper.js
          tar -czvf $DUMP.tar.gz $DUMP
          export NOW=v$(date +'%Y%m%d.%H%M%S')
          echo "NOW=$NOW" >> $GITHUB_ENV
          git config --global user.name $USERNAME
          git config --global user.email $USEREMAIL
          git update-index --refresh
          git add -f $OUTPUT | true
          git add -f $DUMP | true
          if ! git diff-index --quiet HEAD --; then
            git commit -m "fnanendb: autopublish $NOW"
            git push origin HEAD:master
          fi

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.DUMP }}.tar.gz
          path: ${{ env.DUMP }}.tar.gz

      # - name: Commit & Push changes
      #   uses: actions-js/push@master
      #   with:
      #     github_token: ${{ secrets.PAT }}
      #     author_email: ${{ env.USEREMAIL }}
      #     author_name: ${{ env.USERNAME }}
      #     message: "fnanendb: autopublish ${{ env.NOW }}"
      #     branch: master
      #     directory: ${{ env.OUTPUT }}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.DUMP }}.tar.gz
          tag: ${{ env.NOW }}
          token: ${{ secrets.PAT }}
